<?
require_once "file.php";
require_once "news.php";

$file = new File('text.txt');
$newsModel = new News();

if (empty($_GET['page'])) {
    $news = $newsModel->getNews(1, 2);
} else {
    $news = $newsModel->getNews($_GET['page'], 2);
}
?>
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="dist/main.css">
    <title>Lets Rock</title>
</head>
<body>
<div class="content">
    <nav>
        <ul class="top">
            <li><a href="javascript:void(0)">Главная</a></li>
            <li><a href="javascript:void(0)">Каталог</a>
                <ul class="sub">
                    <li><a href="javascript:void(0)">КПК</a></li>
                    <li><a href="javascript:void(0)">Коммуникаторы</a></li>
                    <li><a href="javascript:void(0)">Телефоны</a></li>
                </ul>
            </li>
            <li><a href="javascript:void(0)">Галерея</a></li>
            <li><a href="javascript:void(0)">Контакты</a></li>
        </ul>
    </nav>

    <div class="js-slider slider">
        <div class="js-slide slide show">Содержимое первого слайда</div>
        <div class="js-slide slide">Содержимое второго слайда</div>
        <div class="js-slide slide">Содержимое третьего слайда</div>
        <div class="control">
            <a href="javascript:void(0)" class="js-prev">Предыдущий</a>
            <a href="javascript:void(0)" class="js-point point" data-slide="0"></a>
            <a href="javascript:void(0)" class="js-point point" data-slide="1"></a>
            <a href="javascript:void(0)" class="js-point point" data-slide="2"></a>
            <a href="javascript:void(0)" class="js-next">Следующий</a>
        </div>
    </div>

    <div id="map"></div>
    
    <div>
        <?=$file->get()?>
    </div>

    <div>
        <?foreach ($news['news'] as $item):?>
            <h3><?=$item['name']?></h3>
            <p><?=$item['text']?></p>
            <br>
        <? endforeach; ?>

        <? if(!empty($news['prevPage'])): ?>
        <a href="?page=<?=$news['prevPage']?>">Предыдущая страница</a>
        <? endif; ?>

        <span><?=$news['page']?></span>

        <? if(!empty($news['nextPage'])): ?>
        <a href="?page=<?=$news['nextPage']?>">Следующая страница</a>
        <? endif; ?>
    </div>


</div>
<script src="dist/main.js"></script>
</body>
</html>